// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://facrrgvrdampjdvonwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY3JyZ3ZyZGFtcGpkdm9ud3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDc1NTksImV4cCI6MjA3Mjg4MzU1OX0.tI7FHLA2wVH3HQY1gp9rGGKUT3rYsGmF77d0v4LC2ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});